framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

    serializer:
        name_converter: serializer.name_converter.camel_case_to_snake_case
        enabled: true

    property_info:
        with_constructor_extractor: true

when@test:
    framework:
        test: true
