security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            entry_point: App\Security\ApiAuthenticationEntryPoint
            custom_authenticators:
                - App\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/v1/auth/(register|register-owner|login|refresh)$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/slots/available$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }
